# Generated by Django 2.2.9 on 2020-01-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillim', '0003_auto_20200127_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='alias',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
