# Generated by Django 2.2.9 on 2020-01-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillim', '0004_worker_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='start_time',
            field=models.TimeField(default=None, null=True),
        ),
    ]
