# Generated by Django 2.2.9 on 2020-01-31 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillim', '0008_auto_20200130_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='sick',
            field=models.DateField(default=None, null=True),
        ),
    ]
