# Generated by Django 2.2.9 on 2020-01-31 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillim', '0009_worker_sick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='sick',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
