# Generated by Django 2.2.9 on 2020-01-31 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillim', '0010_auto_20200131_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='current_status',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='alias',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
